/**
 * Copies lesson content from the website (../data.js + ../images) into the app.
 * Run after editing data.js:  npm run sync-content
 *
 * Outputs:
 *   src/content/hangeul.json   – the HANGEUL_DATA object
 *   src/content/images.ts      – static require() map (Metro needs literal paths)
 *   assets/content/**          – only the images the app actually uses
 */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const WEB_ROOT = path.resolve(__dirname, '..', '..');
const APP_ROOT = path.resolve(__dirname, '..');
const OUT_JSON = path.join(APP_ROOT, 'src', 'content', 'hangeul.json');
const OUT_IMAGES_TS = path.join(APP_ROOT, 'src', 'content', 'images.ts');
const OUT_ASSETS = path.join(APP_ROOT, 'assets', 'content');

// Images used by the UI itself (celebration photos, word fallback)
const UI_IMAGES = ['image18.png', 'part2/image26.png', 'image14.png', 'image4.jpeg'];

const src = fs.readFileSync(path.join(WEB_ROOT, 'data.js'), 'utf8');
const data = new Function(`${src}\nreturn HANGEUL_DATA;`)();

const used = new Set(UI_IMAGES);
for (const lesson of data.lessons) {
  for (const step of lesson.steps) if (step.image) used.add(step.image);
}
for (const word of data.words) if (word.image) used.add(word.image);

fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
fs.writeFileSync(OUT_JSON, JSON.stringify(data, null, 2) + '\n');

fs.rmSync(OUT_ASSETS, { recursive: true, force: true });
const images = [...used].sort();
const missing = [];
const byHash = new Map(); // identical files are bundled once
const bundledAs = new Map(); // image key -> copied file
for (const rel of images) {
  const from = path.join(WEB_ROOT, 'images', rel);
  if (!fs.existsSync(from)) {
    missing.push(rel);
    continue;
  }
  const hash = crypto.createHash('sha1').update(fs.readFileSync(from)).digest('hex');
  if (!byHash.has(hash)) {
    const to = path.join(OUT_ASSETS, rel);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    byHash.set(hash, rel);
  }
  bundledAs.set(rel, byHash.get(hash));
}

const lines = [...bundledAs].map(
  ([key, file]) => `  ${JSON.stringify(key)}: require(${JSON.stringify(`../../assets/content/${file}`)}),`
);
fs.writeFileSync(
  OUT_IMAGES_TS,
  `// Generated by scripts/sync-content.js — do not edit by hand.\n` +
    `import type { ImageSourcePropType } from 'react-native';\n\n` +
    `export const IMAGES: Record<string, ImageSourcePropType> = {\n${lines.join('\n')}\n};\n`
);

console.log(`Synced ${data.lessons.length} lessons, ${data.words.length} words, ${bundledAs.size} images (${byHash.size} files).`);
if (missing.length) {
  console.warn(`Missing images (skipped): ${missing.join(', ')}`);
  process.exitCode = 1;
}
